This code compares the performance of matrix multiplication using PyTorch on the GPU and NumPy on the CPU. It also measures the time taken to create a small tensor of zeros. The @ symbol is used for matrix multiplication in PyTorch. The timings help demonstrate the potential speedup gained by utilizing a GPU for certain operations.

In [13]:
import torch
import numpy as np
import time

# Check if a GPU (cuda) is available, otherwise use CPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Print the selected device (either 'cuda' or 'cpu')
print(f"selected devide: {device}")


selected devide: cuda


In [14]:
%%time
# Measure the elapsed time to create a small tensor with zeros
start_time = time.time()
# Matrix operation: creating a tensor of zeros
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time: {elapsed_time:.10f}")



Elapsed Time: 0.0000820160
CPU times: user 48 µs, sys: 248 µs, total: 296 µs
Wall time: 225 µs


In [15]:
# Create 2D tensors
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)



In [16]:
%%time
# Measure the elapsed time for matrix multiplication with PyTorch (GPU)
start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time with GPU (torch): {elapsed_time:.10f}")

Elapsed Time with GPU (torch): 0.0036427975
CPU times: user 916 µs, sys: 3.96 ms, total: 4.88 ms
Wall time: 3.9 ms


In [17]:
%%time
# Measure the elapsed time for matrix multiplication with NumPy (CPU)
start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time with CPU (numpy): {elapsed_time:.10f}")



Elapsed Time with CPU (numpy): 0.1917331219
CPU times: user 95 ms, sys: 97.7 ms, total: 193 ms
Wall time: 192 ms


In [18]:
# Create 4D tensors
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)


In [19]:
%%time
# Measure the elapsed time for 4D matrix multiplication with PyTorch (GPU)
start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time with GPU (torch): {elapsed_time:.10f}")

Elapsed Time with GPU (torch): 0.0026121140
CPU times: user 3.89 ms, sys: 0 ns, total: 3.89 ms
Wall time: 2.85 ms


In [20]:
%%time
# Measure the elapsed time for 4D matrix multiplication with NumPy (CPU)
start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time with CPU (numpy): {elapsed_time:.10f}")

Elapsed Time with CPU (numpy): 0.0914616585
CPU times: user 90.6 ms, sys: 0 ns, total: 90.6 ms
Wall time: 91.6 ms


The following code uses PyTorch's multinomial function to draw 10 samples from a multinomial distribution defined by the probabilities tensor. The multinomial distribution is often used when there are multiple possible outcomes with different probabilities, and it returns the indices of the sampled outcomes. The samples tensor will contain 10 indices, each corresponding to a sampled outcome based on the given probabilities.

In [30]:
# torch.stack, torch.multinomial, torch.trii, torch.triu, input.T / input.transpose, nn.linear, F.softmax

# Define probability tensor
# The tensor represents the probabilities of two outcomes: 0 with 10% probability and 1 with 90% probability.
# 10% or 0.1 => 0, 90% or 0.9 => 1, each probability points to the index of the probability in the tensor
probabilities = torch.tensor([0.1, 0.9])

# Draw 10 samples from the multinomial distribution
# The multinomial distribution is used to sample indices based on the provided probabilities.
# 'num_samples' specifies the number of samples to draw, and 'replacement=True' allows repeated sampling.
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)



tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])


In [37]:
# Define a tensor with values [1, 2, 3, 4, 5]
tensor = torch.tensor([1, 2, 3, 4, 5])

# Use torch.cat to concatenate the original tensor with another tensor containing the value 5
# The 'dim=0' argument specifies that the concatenation should happen along the first dimension (rows).
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5, 5])

In [41]:
# Create a 5x5 matrix filled with ones
matrix_ones = torch.ones(5, 5)

# Use torch.tril to obtain a lower triangular matrix from the input matrix
# torch.tril sets all elements above the main diagonal to zero, creating a lower triangular matrix.
out = torch.tril(matrix_ones)
print(out)

# torch.triu sets all elements above the main diagonal to zero, creating a lower triangular matrix.
out = torch.triu(matrix_ones)
print(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [42]:
# Create a 5x5 matrix filled with zeros
zeros_matrix = torch.zeros(5, 5)

# Create a lower triangular matrix with ones
lower_triangular_ones = torch.tril(torch.ones(5, 5))

# Use masked_fill to replace zeros in the zeros_matrix with negative infinity where lower_triangular_ones is zero
# masked_fill replaces elements where the mask is True with the specified value (in this case, negative infinity).
out = zeros_matrix.masked_fill(lower_triangular_ones == 0, float('-inf'))


# Print the resulting matrix
print(out)


tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [44]:
# Print the exponential values of the tensor 'out'
print(torch.exp(out))


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
