In [1]:
# Import the PyTorch library
import torch

## What are Tensors?

A tensor is a mathematical object representing a multi-dimensional array of numerical values. In the context of machine learning and deep learning frameworks like PyTorch or TensorFlow, tensors are fundamental data structures used to store and manipulate data.

In the context of deep learning, tensors are crucial for representing input data, model parameters, and output predictions. They enable efficient computation on both CPUs and GPUs, making it possible to perform large-scale numerical operations required for training and inference in neural networks.

In [2]:
# Generate a random integer tensor with values between -100 and 100 and shape (6,)
randint = torch.randint(-100, 100, (6,))
randint

tensor([-79, -13,  29, -30,  40,  97])

In [3]:
# Create a 2D tensor with specified values
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
# Create a 2D tensor filled with zeros, with shape (2, 3)
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# Create a 2D tensor filled with ones, with shape (3, 4)
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
# Create an empty tensor with shape (2, 3)
input = torch.empty(2, 3)
input

tensor([[4.0077e+31, 4.5619e-41, 4.0077e+31],
        [4.5619e-41, 4.4842e-44, 0.0000e+00]])

In [8]:
# Create a 1D tensor with values from 0 to 4
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
# Create a 1D tensor with 5 values evenly spaced between 3 and 10
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
# Create a 1D tensor with 5 values logarithmically spaced between 10^-10 and 10^10
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
# Create an identity matrix with size 5x5
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
# Create an empty tensor with the same shape and data type as tensor 'a'
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[2482735057479098226, 7863883273501483066, 2477389231675241573],
        [8103500061356007482, 8104636957719884921, 8243118355370701669]])