This code compares the performance of matrix multiplication using PyTorch on the GPU and NumPy on the CPU. It also measures the time taken to create a small tensor of zeros. The @ symbol is used for matrix multiplication in PyTorch. The timings help demonstrate the potential speedup gained by utilizing a GPU for certain operations.

In [8]:
import torch
import torch_directml
import numpy as np
import time

# Check if a GPU (cuda) is available, otherwise use Directl ML, or CPU
if torch.cuda.is_available():
    device = 'cuda'
elif torch_directml.is_available():
    device = torch_directml.device()
else:
    device = 'cpu'

# Print the selected device (either 'cuda' or 'cpu')
print(f"selected device: {device}")




selected device: privateuseone:0


In [9]:
%%time
# Measure the elapsed time to create a small tensor with zeros
start_time = time.time()
# Matrix operation: creating a tensor of zeros
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time: {elapsed_time:.10f}")



Elapsed Time: 0.0001366138
CPU times: user 80 µs, sys: 198 µs, total: 278 µs
Wall time: 226 µs


In [10]:
# Create 2D tensors
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)



In [11]:
%%time
# Measure the elapsed time for matrix multiplication with PyTorch (GPU)
start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time with GPU (torch): {elapsed_time:.10f}")

Elapsed Time with GPU (torch): 0.0153822899
CPU times: user 0 ns, sys: 19.7 ms, total: 19.7 ms
Wall time: 15.5 ms


In [12]:
%%time
# Measure the elapsed time for matrix multiplication with NumPy (CPU)
start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time with CPU (numpy): {elapsed_time:.10f}")



Elapsed Time with CPU (numpy): 0.1230676174
CPU times: user 29.9 ms, sys: 94.2 ms, total: 124 ms
Wall time: 123 ms


In [13]:
# Create 4D tensors
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)


In [14]:
%%time
# Measure the elapsed time for 4D matrix multiplication with PyTorch (GPU)
start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time with GPU (torch): {elapsed_time:.10f}")

Elapsed Time with GPU (torch): 0.0241825581
CPU times: user 24.6 ms, sys: 0 ns, total: 24.6 ms
Wall time: 24.5 ms


In [15]:
%%time
# Measure the elapsed time for 4D matrix multiplication with NumPy (CPU)
start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Elapsed Time with CPU (numpy): {elapsed_time:.10f}")

Elapsed Time with CPU (numpy): 0.0858514309
CPU times: user 65.8 ms, sys: 21.7 ms, total: 87.5 ms
Wall time: 86 ms


The following code uses PyTorch's multinomial function to draw 10 samples from a multinomial distribution defined by the probabilities tensor. The multinomial distribution is often used when there are multiple possible outcomes with different probabilities, and it returns the indices of the sampled outcomes. The samples tensor will contain 10 indices, each corresponding to a sampled outcome based on the given probabilities.

In [16]:
# torch.stack, torch.multinomial, torch.trii, torch.triu, input.T / input.transpose, nn.linear, F.softmax

# Define probability tensor
# The tensor represents the probabilities of two outcomes: 0 with 10% probability and 1 with 90% probability.
# 10% or 0.1 => 0, 90% or 0.9 => 1, each probability points to the index of the probability in the tensor
probabilities = torch.tensor([0.1, 0.9])

# Draw 10 samples from the multinomial distribution
# The multinomial distribution is used to sample indices based on the provided probabilities.
# 'num_samples' specifies the number of samples to draw, and 'replacement=True' allows repeated sampling.
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)



tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [17]:
# Define a tensor with values [1, 2, 3, 4, 5]
tensor = torch.tensor([1, 2, 3, 4, 5])

# Use torch.cat to concatenate the original tensor with another tensor containing the value 5
# The 'dim=0' argument specifies that the concatenation should happen along the first dimension (rows).
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5, 5])

In [18]:
# Create a 5x5 matrix filled with ones
matrix_ones = torch.ones(5, 5)

# Use torch.tril to obtain a lower triangular matrix from the input matrix
# torch.tril sets all elements above the main diagonal to zero, creating a lower triangular matrix.
out = torch.tril(matrix_ones)
print(out)

# torch.triu sets all elements above the main diagonal to zero, creating a lower triangular matrix.
out = torch.triu(matrix_ones)
print(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [19]:
# Create a 5x5 matrix filled with zeros
zeros_matrix = torch.zeros(5, 5)

# Create a lower triangular matrix with ones
lower_triangular_ones = torch.tril(torch.ones(5, 5))

# Use masked_fill to replace zeros in the zeros_matrix with negative infinity where lower_triangular_ones is zero
# masked_fill replaces elements where the mask is True with the specified value (in this case, negative infinity).
out = zeros_matrix.masked_fill(lower_triangular_ones == 0, float('-inf'))


# Print the resulting matrix
print(out)


tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [20]:
# Print the exponential values of the tensor 'out'
print(torch.exp(out))


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [21]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
# Import the PyTorch neural network module
import torch.nn as nn

# Create a tensor with values [10., 10., 10.]
sample = torch.tensor([10., 10., 10.])

# Create a linear layer with input size 3, output size 3, and no bias term (bias=False)
linear = nn.Linear(3, 3, bias=False)

# Apply the linear transformation to the input tensor 'sample'
output = linear(sample)

# Print the resulting tensor
print(output)


tensor([-0.7089, -3.2878, -0.8331], grad_fn=<SqueezeBackward4>)


In [28]:
# Import the PyTorch functional module
import torch.nn.functional as F

# Create a tensor [1.0, 2.0, 3.0]
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply the softmax function to the tensor along dimension 0
softmax_output = F.softmax(tensor1, dim=0)
# The softmax function is applied element-wise along the specified dimension (dim=0 in this case).

# Print the resulting tensor after softmax
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [29]:
# Initialize an embedding layer
vocab_size = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100) where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output)

tensor([[-1.5163, -0.1229,  0.9176,  2.0541,  1.4191,  0.8168,  0.4307,  0.8136,
          0.6583,  0.9182, -1.6876, -0.2422,  0.4874,  0.4802,  0.6036,  0.8348,
         -0.6920, -0.2389,  0.1228,  0.4565,  0.9333,  1.9761,  0.7832, -0.7447,
          0.5195,  2.0484, -0.4768,  1.2020,  1.9488, -1.9714,  0.0759,  0.1694,
         -0.8946, -0.0329, -0.6312, -0.4724,  0.6246, -0.1703,  0.3183, -0.6580,
         -1.8639,  0.1969, -0.7793, -0.8671,  2.3073,  0.2279,  0.9496, -1.1284,
         -0.3375,  0.7736, -0.9793, -0.1009, -2.0326, -1.0071, -0.8934,  1.1508,
          1.0250,  0.1693,  1.8175,  1.8592, -0.0086, -0.3111,  1.4064, -0.5730,
          0.2898, -0.3062,  0.5688, -0.2987,  0.0876, -0.8802,  0.4868,  0.8665,
          0.4608,  1.5224,  0.2675,  1.0817,  2.8044,  1.4003,  1.4749,  0.9351,
         -0.9346,  1.2667,  0.9881,  0.1590, -0.2454, -1.4435,  1.8560,  0.8051,
         -0.4424, -0.0830, -0.5607, -0.0228, -0.5861, -1.3285, -2.6009,  0.2883,
         -2.2428, -0.8814, -